package br.metodista.ead.ads3.view;

import javax.swing.JOptionPane;
import br.metodista.ead.ads3.model.Valet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luiz Fernando de Souza Matricula: 225272 ADS - EAD - Polo Sorocaba
 */
public class ValetTela extends javax.swing.JFrame {

    private Valet selecionado = null;
    private ValetTableModel modeloValet = new ValetTableModel();
    private DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    public ValetTela() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPainel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelEntrada = new javax.swing.JLabel();
        jFormattedTextFieldPlaca = new javax.swing.JFormattedTextField();
        jPanelDados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Controle de Valet");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelPainel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle de Valet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 36))); // NOI18N
        jPanelPainel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Modelo:");
        jPanelPainel.add(jLabel1);
        jLabel1.setBounds(20, 50, 60, 16);

        jTextFieldModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanelPainel.add(jTextFieldModelo);
        jTextFieldModelo.setBounds(30, 70, 260, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Placa:");
        jPanelPainel.add(jLabel2);
        jLabel2.setBounds(360, 50, 41, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Entrada:");
        jPanelPainel.add(jLabel3);
        jLabel3.setBounds(20, 110, 70, 20);

        jLabel4.setText("Valor:");
        jPanelPainel.add(jLabel4);
        jLabel4.setBounds(310, 110, 33, 16);

        jLabelValor.setBackground(new java.awt.Color(0, 0, 0));
        jLabelValor.setForeground(new java.awt.Color(51, 255, 0));
        jLabelValor.setOpaque(true);
        jPanelPainel.add(jLabelValor);
        jLabelValor.setBounds(330, 130, 180, 30);

        jLabelEntrada.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEntrada.setForeground(new java.awt.Color(51, 255, 0));
        jLabelEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEntrada.setOpaque(true);
        jPanelPainel.add(jLabelEntrada);
        jLabelEntrada.setBounds(30, 130, 180, 30);

        try {
            jFormattedTextFieldPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPlaca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanelPainel.add(jFormattedTextFieldPlaca);
        jFormattedTextFieldPlaca.setBounds(370, 70, 140, 30);

        jPanelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanelDados.setLayout(null);

        jTableDados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableDados.setModel(modeloValet);
        jTableDados.setColumnSelectionAllowed(true);
        jTableDados.getTableHeader().setReorderingAllowed(false);
        jTableDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDados);
        jTableDados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableDados.getColumnModel().getColumnCount() > 0) {
            jTableDados.getColumnModel().getColumn(0).setResizable(false);
            jTableDados.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableDados.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        jPanelDados.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 520, 300);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonFechar))
                .addGap(5, 5, 5)
                .addComponent(jPanelDados, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed

        Object[] options = {"Sim", "Não"};

        if (JOptionPane.showOptionDialog(this, "Deseja Sair?", "Atenção",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null,
                options, options[1]) == JOptionPane.YES_OPTION) {

            dispose();

        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        jButtonFecharActionPerformed(null);

    }//GEN-LAST:event_formWindowClosing

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed

        Valet v = new Valet(jTextFieldModelo.getText(),
                jFormattedTextFieldPlaca.getText(), new Date());
        try {
            modeloValet.adicionar(v);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        limparCampos();
        jTextFieldModelo.grabFocus();

    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTableDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosMouseClicked

        Valet v = modeloValet.getValet(jTableDados.getSelectedRow());
        v.setSaida(new Date());
        jTextFieldModelo.setText(v.getModelo());
        jFormattedTextFieldPlaca.setText(v.getPlaca());
        jLabelEntrada.setText(df.format(v.getEntrada()));
        //a data e hora de saida ocorre no evento click da tabela.
        v.setValor(calcularPreco(v.getEntrada(), v.getSaida()));
        jLabelValor.setText("R$ " + String.valueOf(v.getValor()));
        selecionado = v;


    }//GEN-LAST:event_jTableDadosMouseClicked

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        limparCampos();
        jTextFieldModelo.grabFocus();

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed

        try {
            modeloValet.remover(selecionado);
        } catch (Exception ex) {
            Logger.getLogger(ValetTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();

    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValetTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValetTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValetTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValetTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValetTela().setVisible(true);

            }
        });
    }

    private void limparCampos() {

        jTextFieldModelo.setText("");
        jFormattedTextFieldPlaca.setText("");
        jLabelEntrada.setText("");
        jLabelValor.setText("");
        selecionado = null;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEntrada;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables

    private Double calcularPreco(Date entrada, Date saida) {

        //variavel saida declarada para que no momento da seleção do registro
        //a data e hora entrem no calculo de imediato e não após
        //o evento do botão finalizar
        long diferenca = saida.getTime() - entrada.getTime(); //em milissegundos
        //Tempo em milissegundos divido por 1000 retorna segundos
        //dividindo segundos por 60 retorna minutos
        //dividindo minutos por 60 retorna hora
        int horas = (int) (diferenca / 1000 / 60 / 60);
        int minutos = (int) (diferenca / 1000 / 60);

        double total = horas * 3;
        if (minutos != 0) {

            total += 3;

        }

        return total;
    }
}
